#!/usr/bin/env python3
"""Emit a pool_run batch script straight from clips_spec.py.

    python3 make_batch.py videos_v1.sh s01 s10     # a shot range, inclusive
    python3 make_batch.py videos_v1.sh             # every shot

Generating the .sh from the spec (rather than hand-writing it) means the prompt
that ships to Seedance is byte-identical to the one shown in storyboard.html.
Then:
    caffeinate -is python3 ../pool_run.py videos_v1.sh outputs/video1 7
"""
import importlib.util
import shlex
import sys
from pathlib import Path

PROJ = Path(__file__).parent
spec = importlib.util.spec_from_file_location("clips_spec", PROJ / "clips_spec.py")
cs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cs)

out = sys.argv[1]
names = [c[0] for c in cs.CLIPS]
if len(sys.argv) > 3:
    lo = next(i for i, n in enumerate(names) if n.startswith(sys.argv[2]))
    hi = next(i for i, n in enumerate(names) if n.startswith(sys.argv[3]))
    clips = cs.CLIPS[lo:hi + 1]
else:
    clips = cs.CLIPS

lines = ["#!/bin/bash", "# generated by make_batch.py — do not hand-edit", ""]
total = 0
for name, dur, prompt, refs in clips:
    parts = [f"gen {name} {dur} {shlex.quote(prompt)}",
             f"--start-image $F/{name}.png"]
    # An END frame, if one exists, pins where the shot must ARRIVE. Two uses:
    #   - a transformation Seedance keeps refusing to perform (the clay figure
    #     growing a third arm): give it the before AND the after, and it has to
    #     interpolate between them rather than invent its own idea of the action.
    #   - a HOLD: set the end frame equal to the start frame and the clip has
    #     nowhere to drift to (stops it inventing a second Earth).
    if (PROJ / "frames_end" / f"{name}.png").exists():
        parts.append(f"--end-image frames_end/{name}.png")
    parts += [f"--image $A/{r}.png" for r in refs]
    lines.append(" ".join(parts))
    total += dur

(PROJ / out).write_text("\n".join(lines) + "\n")
print(f"{out}: {len(clips)} clips, {total}s of video, ~{total * 3:.0f} credits (480p std)")
print(f"  {clips[0][0]} .. {clips[-1][0]}")
