#!/bin/bash
# THE CUTOFF (Donner Party) — scene start frames + title cards (Nano Banana Pro).
# Run AFTER anchors_v1.sh. 5 concurrent max. All 16:9.
cd /Users/dawndrain/Code/videogen
A=donner_party/anchors; F=donner_party/frames; mkdir -p $F

S="Photorealistic, shot on 35mm film, 1846 American frontier period, muted earth tones, natural light. Characters keep exactly the same faces, hair and clothes as in the reference images. Authentic 1840s overland emigrant clothing, oxen not horses pull the wagons, no modern objects. ONE single continuous photograph filling the whole frame, no borders, no collage. No text or captions unless explicitly described."

img() {
  local name="$1"; shift
  local out
  if [ -f "$F/$name.png" ]; then echo "SKIP $name"; return; fi
  for attempt in 1 2; do
    out=$(./gen.py image "$@" --aspect_ratio 16:9 2>"$F/$name.err" | tail -1)
    if [ -f "$out" ]; then cp "$out" "$F/$name.png"; echo "OK $name"; return; fi
    sleep 5
  done
  echo "FAIL $name"
}

# ---- Cold open + Act I: the shortcut ----
img f_v0_letter "The ranch porch from the reference location in warm late-afternoon light: the 13-year-old girl from the reference sits at the small wooden table, dipping a pen in an inkwell, a half-written letter before her, a jar of wildflowers beside it. Her face is calm and healthy, her calico dress clean and mended. $S" --image $A/napa_porch.png --image $A/virginia_reed.png &
img f_a1_departure "A Springfield Illinois street in April 1846: an enormous two-story covered wagon, twice the height of an ordinary one, with a small stovepipe poking through its canvas roof, rolls out drawn by four yoke of oxen, leading a line of ordinary covered wagons. The proud businessman from the reference rides a gray saddle horse alongside; the 13-year-old girl from the second reference rides a small brown pony beside him; townsfolk wave from board sidewalks. $S" --image $A/james_reed.png --image $A/virginia_reed.png &
img f_a2_prairie "Golden evening on the spring prairie, covered wagons drawn into a circle, cookfires, oxen grazing loose. In the foreground the schoolteacher from the reference sits on a wagon tongue reading aloud from her leather journal, spectacles on, while the white-haired farmer from the second reference lights his pipe beside her, both easy and content. $S" --image $A/tamsen_donner.png --image $A/george_donner.png --image $A/prairie_train.png &
img f_a3_warning "Night at Fort Laramie, 1846: adobe walls and tipis in the background, a small campfire in the foreground. The leathery old mountain man in buckskins from the reference leans forward across the fire, speaking gravely, one finger raised, to the proud businessman from the second reference, who holds an open printed emigrant guidebook and looks unconvinced. The schoolteacher from the third reference stands at the edge of the firelight, listening with folded arms. $S" --image $A/clyman.png --image $A/james_reed.png --image $A/tamsen_donner.png &
img f_a4_vote "Morning at a fork of two wagon roads on open sage plain: to the left, a long line of covered wagons rolls away north; to the right, a smaller cluster of twenty wagons stands waiting. In the foreground a knot of emigrant men raise their hands in a vote around the white-haired farmer from the reference, who holds his hat in his hands, embarrassed. The schoolteacher from the second reference watches from beside a wagon wheel, apart, arms folded, uneasy. $S" --image $A/george_donner.png --image $A/tamsen_donner.png &
wait

img f_a5_bridger "Fort Bridger, 1846: two rough log cabins and an empty pole corral on a sage plain. The proud businessman from the reference stands reading a note nailed to the corral gatepost; the paper reads exactly: Gone ahead to guide you through. Follow my trail. - L. W. Hastings. Behind him other emigrants wait beside their oxen, watching his face. $S" --image $A/james_reed.png &
img f_b1_wasatch "The boulder-choked aspen canyon from the reference: the wagon train stalled nose to tail among the rocks, a dozen emigrant men in sweat-soaked shirts swinging axes at the tangled aspens and dragging brush aside, a half-cut path of fresh stumps ahead. In the foreground the gentle bearded bachelor from the second reference wipes his face with his sleeve, exhausted, axe in hand. $S" --image $A/wasatch.png --image $A/stanton.png &
img f_b2_saltdesert "Night on the blinding salt flats from the reference, under a full moon: a broken line of covered wagons far apart on the white crust, staggering oxen, one ox lying down in its yoke, a woman carrying a child on her back beside a wagon, everything white and unreal. $S" --image $A/salt_desert.png &
img f_b3_cache "Dawn on the salt flats: the enormous two-story palace wagon from the departure stands abandoned, door open, half-buried furniture and a hole dug in the salt crust beside it where the businessman from the reference and his wife from the second reference lower a wooden chest. The small 8-year-old girl from the third reference stands apart, clutching something tiny hidden in her cupped hands against her chest. $S" --image $A/james_reed.png --image $A/margaret_reed.png --image $A/patty_reed.png &
img f_b4_snyder "A steep sandy hill on the trail, two ox teams tangled together, wagons jammed. The burly red-faced teamster from the reference stands on the wagon tongue with his bullwhip raised high over the oxen, screaming; the proud businessman from the second reference strides toward him with a raised open hand, commanding him to stop; the businessman's wife from the third reference reaches for her husband's arm to hold him back. High tension, nothing yet struck. $S" --image $A/snyder.png --image $A/james_reed.png --image $A/margaret_reed.png &
wait

img f_b5_banish "Night camp, wagons dark, a single lantern. The businessman from the reference sits on his horse at the edge of camp, stripped of his gear, coatless, about to ride into the dark alone. The 13-year-old girl from the second reference reaches up to him, pressing a long bundle wrapped in a blanket into his hands, her face fierce with tears. $S" --image $A/james_reed.png --image $A/virginia_reed.png &
img f_b6_hardkoop "A dusty desert trail in harsh afternoon light: a frail white-bearded old man in ragged clothes sits slumped on a rock beside the track, his worn boots split open, watching a covered wagon roll away from him. Walking beside the wagon, not looking back, the tall blond cold-faced man from the reference. The wagon and the old man separated by a widening gap of empty trail. $S" --image $A/keseberg.png &
img f_b7_stanton "A cold autumn river meadow, first dusting of snow on the far peaks: the gentle bearded bachelor from the reference rides in on a mule at the head of seven heavily loaded pack mules, raising one hand in greeting; beside him ride the two young Miwok men from the second reference in their serape and poncho. Ahead of them, ragged emigrants run forward from their wagons, arms raised, first joy on their faces. $S" --image $A/stanton.png --image $A/luis_salvador.png &
img f_c1_lake "The dark alpine lake and sheer granite wall from the reference, storm clouds pouring over the pass notch like smoke. In the foreground the Irish farmer from the second reference stands looking up at the mountain, hat in hand, crossing himself, the first snowflakes hanging in the air around him. $S" --image $A/truckee_lake.png --image $A/breen.png &
img f_c2_pass "High on the pass in a driving snowstorm, drifts to the oxen's bellies: abandoned wagons tilted in the snow behind, a broken line of emigrants carrying children and bundles, all stalled. The bearded bachelor from the reference wades back downhill through the deep snow toward them, shouting, pointing up at the invisible summit; a mother has collapsed against a dead pine with a bundled child in her arms. $S" --image $A/stanton.png --image $A/summit_snow.png &
wait

img f_c3_cabins "The lake shore in falling snow: three rough log cabins in a clearing, one still being roofed — two gaunt men stretching a raw ox-hide across the rafters, another notching a log with an axe, children carrying pine boughs, everything gray and hurried, snow already a foot deep. $S" --image $A/truckee_lake.png &
img f_c4_alder "Inside the buried canvas-and-brush shelter from the reference, firelight: the gaunt white-haired old man from the second reference lies propped against rolled quilts, his bandaged right arm across his chest; the schoolteacher from the third reference kneels beside him, re-wrapping the bandage, smiling deliberately for two small daughters who watch from the shadows. $S" --image $A/alder_tent.png --image $A/george_snow.png --image $A/tamsen_snow.png &
img f_c5_breen "The dim cabin interior from the reference: the gaunt Irish farmer from the second reference sits at the plank table writing in a small diary with a stub of pencil by the light of the single grease-lamp, lips moving as he writes, sleeping children bundled like cordwood along the wall behind him. $S" --image $A/cabin_interior.png --image $A/breen_snow.png &
img f_c6_hides "The dim cabin interior from the reference: the gaunt mother from the second reference holds out a gold pocket watch across the plank table by candlelight to the rawboned gray-haired farmer from the third reference, whose hand hesitates above it. Behind them a kettle steams over the fire and thin children watch a strip of ox-hide boiling in it. $S" --image $A/cabin_interior.png --image $A/margaret_snow.png --image $A/graves_sr.png &
img f_c7_burial "A snow trench in gray falling snow beside the cabins: a long blanket-wrapped form lies at the bottom, and around the trench a half-circle of gaunt blanket-wrapped emigrants stand with bowed heads, breath-fog rising, while the Irish farmer from the reference reads from his small prayer book. $S" --image $A/breen_snow.png &
wait

# ---- Act IV: the Forlorn Hope ----
img f_d1_snowshoes "The dim cabin interior from the reference: the rawboned gray-haired farmer from the second reference kneels by the fire bending a steamed strip of oxbow wood into a hoop, rawhide lattice snowshoes finished in a stack beside him; the lean buckskin hunter from the third reference watches from the table, arms crossed, grim. $S" --image $A/cabin_interior.png --image $A/graves_sr.png --image $A/eddy_snow.png &
img f_d2_depart "The white ocean of snowdrifts from the reference under an iron sky: a single file of seventeen tiny dark figures on improvised snowshoes crossing the vast white slope, bent under small packs, the granite wall of the pass looming ahead. Wide desolate shot, the people small as ants. $S" --image $A/summit_snow.png &
NOWAGON="This is a party of snowshoe walkers lost in high mountain wilderness: there are NO wagons, NO carts, NO oxen, NO horses, NO animals and NO camp equipment anywhere in the scene — only deep snow, pines, and the people with their small shoulder packs and improvised snowshoes."
img f_d3_stanton "Morning in deep snow: the burnt-out black ring of last night's fire, cold and smokeless. The gentle bachelor from the reference sits alone on a snow-covered log beside the dead fire, calmly packing his white clay pipe, eyes weak and unfocused, at peace. Behind him and to the right, the tall young woman from the second reference stands on her snowshoes at the head of the departing single file of walkers, turned back toward him, stricken. $NOWAGON $S" --image $A/stanton_snow.png --image $A/mary_snow.png &
img f_d4_death_camp "Gray dawn after a blizzard in deep snow: a fire-pit sunk two feet down into the drifts, dead and black. Around it, wide apart from one another, five gaunt hooded survivors wrapped head to foot in frozen blankets sit motionless in the snow, each turned away from the fire and from the others, no one looking at anyone. Terrible stillness. $NOWAGON $S" --image $A/summit_snow.png &
img f_d5_warning "Night in a snow camp among pines, a small dying campfire: the buckskin hunter from the reference crouches beside the two young Miwok men from the second reference, shaking one awake, pressing a powder horn into his hands, whispering urgently, glancing back over his own shoulder toward the dark blanket-wrapped shapes of the other sleepers in the snow. The two men are half-risen, gathering their serapes. $NOWAGON $S" --image $A/eddy_snow.png --image $A/luis_salvador.png &
wait

img f_d6_ridge "A bare wind-scoured ridge above the treeline, thin snow over rock: a straggling single file of gaunt survivors on snowshoes crossing it. The buckskin hunter from the reference has stopped mid-line and turned to look back along the empty ridge behind them, eyes closed, face rigid; the tall young woman from the second reference looks back too. A gap in the line where someone is missing. $S" --image $A/eddy_snow.png --image $A/mary_snow.png &
img f_d7_ranch "The green foothill valley and adobe ranch house from the reference in soft January light: at the ranch door, the buckskin hunter from the second reference — scarecrow-thin, snow-burned, barely upright — sags in the doorway, held up under one arm by a young Miwok man; a settler woman in an apron has flung the door open, one hand to her mouth. $S" --image $A/johnsons_ranch.png --image $A/eddy_snow.png &

# ---- Act V: relief ----
img f_e1_sutter "A candlelit adobe room at Sutter's Fort, rain on the small window: the businessman from the reference — thinner now, trail-worn — leans over a rough map of the mountains spread on a table, both fists on the table, face desperate; across from him a heavyset balding Swiss gentleman in a brown coat spreads his hands in refusal. $S" --image $A/james_reed.png &
img f_e2_relief1 "Dusk on a vast snowfield where the cabins should be — nothing but smooth white drifts and a few chimney-stones. Seven rescuers in heavy coats with packs stand scattered on the snow, shouting into the emptiness. In the foreground, rising out of a dark hole in the snow itself, the head and raised hand of the gaunt woman from the reference, ragged shawl over her head, looking up at them as if at angels. $S" --image $A/murphy_woman.png --image $A/summit_snow.png &
img f_e3_patty "The mouth of a snow-tunnel entrance down into a buried cabin: the small 8-year-old girl from the reference, thin and grave in her pinafore under a wrapped blanket, is being handed back down into the hole by a rescuer in a heavy coat, while the gaunt mother from the second reference is bodily turned away westward by another rescuer, her hand still stretched back toward the child. $S" --image $A/patty_reed.png --image $A/margaret_snow.png &
img f_e4_reunion "A snow trail among pines: a line of rescuers with packs coming east meets the ragged survivors coming west. In the center the 13-year-old girl from the reference — thin, in a ragged blanket — is caught mid-run and mid-stumble in the deep snow, arms out; ten feet ahead the businessman from the second reference has dropped his pack and fallen to his knees in the snow, arms open, face broken with joy. $S" --image $A/virginia_snow.png --image $A/james_reed.png &
wait

img f_e5_doll "At the snow-tunnel mouth of the buried cabin: the businessman from the reference, kneeling in the snow, lifts the small 8-year-old girl from the second reference up out of the dark hole into the light. She holds out her small fist to him, open, showing a tiny carved wooden doll on her palm. His face is laughing and weeping at once. $S" --image $A/james_reed.png --image $A/patty_reed.png &
img f_e6_tamsen "Inside the buried shelter from the reference, firelight: the gaunt schoolteacher from the second reference kneels holding the faces of three small girls in wrapped travel blankets, her forehead against theirs; a rescuer holds the tent flap open, snow-light streaming in, his other hand impatient on the rope that links the children. In the shadows behind her, the dying white-haired man from the third reference watches from his quilts, calm. $S" --image $A/alder_tent.png --image $A/tamsen_snow.png --image $A/george_snow.png &
img f_e7_keseberg "Late April at the lake camp, snow half-melted into gray slush, wrecked cabin timbers and scattered goods everywhere: amid the wreckage the tall matted-blond man from the reference sits utterly composed, wrapped in a dark buffalo robe, looking up at three rough men in heavy coats who stand a careful distance away, one holding a coil of rope, all staring at him. $S" --image $A/keseberg_snow.png --image $A/truckee_lake.png &
img f_e8_paradise "From the crest of the pass looking west: the snow ends at the viewers' feet and beyond it the land falls away into an immense green valley in full wildflower spring, mist burning off, rivers shining. On the crest, small in frame, a ragged line of survivors and rescuers ON FOOT stands stopped, silhouetted, looking down at the green. There are NO wagons and NO animals; everyone is on foot carrying small packs. $S" --image $A/summit_snow.png &
img f_f1_letter_end "The ranch porch from the reference in warm late-afternoon light: the 13-year-old girl from the second reference sits at the small wooden table, healthy again in her clean calico dress, folding a finished letter, looking up directly into the camera with a level, grown-up gaze far older than her face. $S" --image $A/napa_porch.png --image $A/virginia_reed.png &
wait

# ---- Title cards (verbatim text — Nano Banana does exact text) ----
img t_title "A dark cinematic title card: the sheer granite mountain wall and pass notch from the reference in storm light, nearly black, with elegant white period serif letters centered reading exactly: THE CUTOFF. No other text. $S" --image $A/truckee_lake.png &
img t_date1 "A cinematic title card, plain aged-paper background like an 1840s letter, centered small dark serif text reading exactly: SPRINGFIELD, ILLINOIS - APRIL 1846. No other text or decoration. Photorealistic paper texture." &
img t_forlorn "A cinematic title card, near-black background with faint blowing snow, centered white serif text reading exactly: THE FORLORN HOPE - DECEMBER 16. No other text." &
img t_end "A cinematic title card, near-black background, three centered lines of white serif text reading exactly: Of the 87 emigrants who took the Hastings Cutoff, 48 survived. Only the Reed and Breen families came through whole. The lake is called Donner Lake now. No other text. $S" &
wait
echo FRAMES_DONE
