#!/bin/bash
# v19 changes (STD, 480p): python3 ../tools/pool_run.py videos_v19.sh outputs/video19 4
# NOTE: fast mode FAILS server-side on any job with an --audio ref (8/8 failures, generic
# "failed" status); these are all voice-ref dialogue shots, so they must run std.
# n1_bridge2: "nobody dies this time" -> "haven't died since the Bronze Age" (last death was ~33 yrs back)
# n5_type2:   "never copying by hand again" -> one copy / one building / one fire (Tertius did the copying)
# p4_exit4:   same staff-door beat, well-kept room (new frame f_p4_room_tidy.png, nano-banana'd from 7_2_exit_80)
# q7b_consider: NEW ending beat - weighing a third bust-out; chained from q7_fail2's last frame

NEG="Photorealistic, natural human motion and facial performance, correct anatomy and proportions. No slow motion unless stated. No text, captions or subtitles appearing anywhere. Characters keep exactly the same faces and clothes as in the reference images for the entire clip. Each character appears exactly once. Voices match the provided audio reference."
WRENC="Wardrobe and character lock: Cass is 55, lean, grey-streaked dark hair, trimmed grey beard, watchful grey eyes, wearing a dark ink-stained doublet under a heavy charcoal cloak. Renaissance walled river city, tall narrow timber houses, barges, waterwheels."
WCASS="Wardrobe and character lock: Cass is 17, white, lean, pale, short dark tousled hair, watchful grey eyes, wearing a plain heather-grey t-shirt, dark slim jeans. The sleek minimal 2044 bedroom at night: concrete wall, low platform bed, steady warm lamp, city glow through the window. The room is otherwise completely empty - no other people."
EXITSEQ="the tester's exit sequence: eyes closing in concentration, both hands raised to chest height with palms facing each other, then three slow deliberate motions - the left palm passing flat across the right, both hands rotating once around each other, then both hands closing to fists and opening again"

gen n1_bridge2 10 "Cass stands on the stone bridge at dusk taking in the walled river city: waterwheels turning, barges, chimney smoke. He looks down at his older hands, touches his grey beard, and takes stock out loud, his voice matching the audio reference: 'Fifty years old. Ten till the gate.' A beat. He points at the city like he's giving it fair warning: 'And I have not died since the BRONZE AGE. This should be easy.' The bridge is otherwise completely empty - no other people. $WRENC $NEG" --start-image $F/5_1_city_arrival.png --image $A/cass_55.png --audio $A/voice/cass_adult_brit.m4a

gen n5_type2 12 "Cass holds a single tiny metal letter up to the candlelight between finger and thumb, over a tray of hundreds of identical letters. Off-screen a young apprentice asks: 'A thousand little letters... why?' Cass, still admiring the type, his voice matching the audio reference: 'Because last time, everything I knew existed in ONE copy. In ONE building. Which caught ONE fire.' He drops it in the tray with a satisfying click. The workshop is otherwise completely empty - no other people visible. $WRENC $NEG" --start-image $F/5_4_type_tray.png --image $A/cass_55.png --audio $A/voice/cass_adult_brit.m4a

gen p4_exit4 12 "Morning light in the tidy well-kept boarding-house room. Cass, eighty now, stands at the window; outside, the old touched woman passes and nods to him through the glass. He nods back. He steps to the middle of the room, straightens his jacket, and says out loud to the empty room - his own lips clearly moving, in the same measured dry British accent as the audio reference, aged: 'Five lifetimes. Every chore, every gate...' a small smile, '...and I am leaving through the staff door.' He performs $EXITSEQ, precise and unhurried - and on the final motion the room floods to pure white. The room stays exactly as in the start image, clean and cared-for. There is absolutely no narrator, no voiceover, no off-screen voice; the only voice heard is the old man speaking on camera. $NEG" --start-image $F2/f_p4_room_tidy.png --image $A/cass_70.png --audio $A/voice/cass_adult_brit.m4a

gen q7b_consider 10 "The sleek minimal 2044 bedroom at night. Cass lies on his back on the low bed staring at the ceiling, exactly as in the start image. Slowly he sits up on the edge of the bed and looks down at his own two open hands. Quietly, completely level, his voice matching the audio reference: 'Maybe I'm home.' A long beat. 'Maybe I'm five levels deep.' He raises both hands to chest height, palms facing each other, as if about to begin a practiced gesture - and holds there, perfectly still. Locked-off static camera. $WCASS $NEG" --start-image $F2/f_q7b_consider.png --image $A/cass_17.png --audio $A/voice/cass_teen.m4a
