# v13 retakes (STD, 480p, run via: python3 ../pool_run.py videos_v13.sh outputs/video13 4)
# n9: Cass must actually be IN the shot with the widow
# r8/r9: humbler Cass — smart high-schooler, not genius (Dawn note)
# p2: "The Long Game" chalkboard + spoken name

NEG="Photorealistic, natural human motion and facial performance, correct anatomy and proportions. No slow motion unless stated. No text, captions or subtitles appearing anywhere. Characters keep exactly the same faces and clothes as in the reference images for the entire clip. Each character appears exactly once. Voices match the provided audio reference."
VBRIT="Cass speaks in the same measured, dry, understated British accent as the rest of the film - calm RP English delivery, never American, never theatrical. There is no narrator and no voiceover; only characters visible on screen speak, lips moving."
WREN="Wardrobe and character lock: Cass is 55, lean, grey-streaked dark hair, trimmed grey beard, watchful grey eyes, wearing a dark ink-stained doublet under a heavy charcoal cloak. The widow is in her seventies, small, wiry, in a black widow's dress and white linen coif, bright unfocused eyes. Renaissance walled river city, tall narrow timber houses, barges, waterwheels."
WMOD="Wardrobe and character lock: the uncle is 70, silver-haired, weathered handsome face, brown tweed three-piece suit. Peter is mid-twenties, bright anxious face, neat side-parted sandy hair, slightly oversized grey suit. The year is 1926."

gen n9_sixty3 6 "Wide two-shot of the busy print-shop floor, presses working, pages everywhere. In the LEFT foreground, clearly visible in frame the entire clip, Cass - older, tired - pauses mid-task at a press, ink on his hands, and looks up. Across the floor the old widow lifts her head, meets his eye, and nods once. He nods back, the smallest tired smile. Both Cass and the widow remain visible in the frame together. The frame washes gently to white over the last second. $WREN $NEG" --start-image $A/loc_print_shop.png --image $A/cass_55.png --image $A/touched_woman.png

gen r8_glass2 8 "The man holds a cloudy lumpy glass vessel up to the furnace light between two fingers, unimpressed: 'First - we're going to need better glass.' Off-screen, the young scribe, wounded: 'That is the finest glass in the city.' The man turns the vessel over, opens his mouth to explain how, and stops - he has no idea. A long beat. The man, quieter: '...How do you MAKE glass, exactly?' $VBRIT $NEG" --start-image $F/4_4_workshop.png --image $A/cass_45.png --audio $A/voice/cass_adult_brit.m4a

gen r9_acid3 12 "The man tends the glass retort and dictates, pacing, reaching hard for half-remembered schoolwork: 'Take this down, Tertius. Sulfuric acid. It reacts with... nearly everything. Metals. Sugar. I want to say... salts? It is also highly corrosive, and will damage your skin.' At the table, Tertius - a young man in his early twenties - writes with agonizing slowness, murmuring in a young adult male voice only what he actually writes: '...sulfuric... acid... will damage... your skin.' The man closes his eyes for one brief pained moment and keeps working. $VBRIT $NEG" --start-image $F/4_5_vitriol.png --image $A/cass_45.png --audio $A/voice/cass_adult_brit.m4a

gen p2_board3 10 "Peter leads his uncle into the firm's workroom: the brass pod machine half-assembled, engineers at work around it, the chalkboard exactly as in the start image, its writing unchanged the entire clip. The old man stops dead at the sight of the machine. Peter steps beside it and spreads his arms proudly, his voice matching the audio reference: 'And we're calling it... The Long Game.' A beat. The old man's face does absolutely nothing at all. Peter: 'Good, right?' The old man, perfectly flat and dry-British: 'Catchy.' $WMOD $NEG" --start-image $F2/f_p2_longgame.png --image $A/cass_70.png --audio $A/voice/peter.m4a
