# v14 retakes (STD, 480p, run via: python3 ../pool_run.py videos_v14.sh outputs/video14 2)
# b8: dub was bad -> full retake with "The Long Game" + pan follows the point + old woman visible
# p2: kill the pre-existing second Cass (only silver-haired man is the uncle)

NEG="Photorealistic, natural human motion and facial performance, correct anatomy and proportions. No slow motion unless stated. No text, captions or subtitles appearing anywhere. Characters keep exactly the same faces and clothes as in the reference images for the entire clip. Each character appears exactly once. Voices match the provided audio reference."
WMOD="Wardrobe and character lock: the uncle is 70, silver-haired, weathered handsome face, brown tweed three-piece suit. Peter is mid-twenties, bright anxious face, neat side-parted sandy hair, slightly oversized grey suit. The year is 1926."
VBRIT="Cass speaks in the same measured, dry, understated British accent as the rest of the film - calm RP English delivery, never American, never theatrical. There is no narrator and no voiceover; only characters visible on screen speak, lips moving."

gen b8_leave2 10 "The boy talks fast and urgently at the weathered villager, hands up, his voice matching the audio reference: 'How do I get out of here? I was playing this game - The Long Game - at the arcade? Now how do I get out?' The villager leans slowly away from him, deeply uncomfortable, then raises one arm and points across the village; the camera pans IN THE SAME DIRECTION as his pointing arm, following his point until, far across the village, the tiny distant figure of an old woman sitting outside her hut comes into view. The villager, in a gravelly older male voice: '...Go talk to her. If you're going to be acting so crazy.' Bronze-age village, packed earth, thatch roundhouses. $NEG" --start-image $F2/f_b6_villager.png --image $A/cass_17.png --image $A/touched_woman.png --audio $A/voice/cass_teen.m4a

gen r9_acid4 12 "The man tends the glass retort and dictates, pacing, reaching hard for half-remembered schoolwork: 'Take this down, Tertius. Sulfuric acid. It reacts with... nearly everything. Metals. Sugar. I want to say... salts? It is also highly corrosive, and will damage your skin.' While the man dictates, Tertius - a young man in his early twenties at the table - writes with agonizing slowness, head down, mouth CLOSED, never echoing or mouthing the man's words. Only after the man finishes does Tertius murmur in his own younger voice, reading back only what he actually wrote: '...sulfuric... acid... will damage... your skin.' The man closes his eyes for one brief pained moment and keeps working. $VBRIT $NEG" --start-image $F/4_5_vitriol.png --image $A/cass_45.png --audio $A/voice/cass_adult_brit.m4a

gen p2_board4 10 "Peter leads his uncle into the firm's workroom: the brass pod machine half-assembled, and TWO engineers at work around it - both clean-shaven YOUNG men in their twenties with dark hair, shirtsleeves and waistcoats, heads down at their benches. The uncle is the ONLY silver-haired person in the room, and the only elderly person; nobody in the room resembles him. The chalkboard exactly as in the start image, its writing unchanged the entire clip. The old man stops dead at the sight of the machine. Peter steps beside it and spreads his arms proudly, his voice matching the audio reference: 'And we're calling it... The Long Game.' A beat. The old man's face does absolutely nothing at all. Peter: 'Good, right?' The old man, perfectly flat and dry-British: 'Catchy.' $WMOD $NEG" --start-image $F2/f_p2_longgame.png --image $A/cass_70.png --audio $A/voice/peter.m4a
