#!/bin/bash
# Walter's Deal — scene start frames + title cards (Nano Banana Pro).
# Run AFTER anchors_v1.sh + anchors_v1b.sh. 5 concurrent max.
cd /Users/dawndrain/Code/videogen
A=walters_deal/anchors; F=walters_deal/frames; mkdir -p $F

S="Photorealistic, shot on 35mm film, late-1980s Central-European look, muted colors, practical lighting. Characters keep exactly the same faces, hair and clothes as in the reference images. No text or captions unless explicitly described."
S2="Photorealistic, shot on 35mm film, retro-futurist 1990s Central-European look, muted colors. Characters keep exactly the same faces, hair and clothes as in the reference images. No text or captions unless explicitly described."

img() {
  local name="$1"; shift
  local out
  if [ -f "$F/$name.png" ]; then echo "SKIP $name"; return; fi
  for attempt in 1 2; do
    out=$(./gen.py image "$@" --aspect_ratio 16:9 2>"$F/$name.err" | tail -1)
    if [ -f "$out" ]; then cp "$out" "$F/$name.png"; echo "OK $name"; return; fi
    sleep 5
  done
  echo "FAIL $name"
}

# ---- Act I: basement ----
img f_a1_basement "Midnight in a cluttered suburban basement laboratory: TWO identical glass teleport booths exactly like the reference machine stand on opposite sides of the room, both wrapped in frozen fountains of black cables. The young scientist from the reference stands at the small wooden console with the blue button, white lab coat on, a white rat visible inside the NEAR booth. Bookshelves, animal cages in a dark corner, one hanging work lamp. $S" --image $A/walter_young.png --image $A/booth.png &
img f_a2_paper "The young scientist from the reference sits at a plain 1980s kitchen table at morning, gripping an open newspaper and scowling at it. The front page headline reads exactly: THE INVENTOR OF BEAMING - with a grainy photo of him below it. Toast and coffee untouched. $S" --image $A/walter_young.png &
img f_a3_mob "A small elegant suburban family house with a proud oak tree, its front lawn overrun: TV reporters with microphones and shoulder cameras, six identical businessmen in gray suits with red ties, and costumed science-fiction fans holding hand-painted signs reading exactly BEAM ME UP, WALTER! and WE BELIEVE! Police officers holding the line. Bright afternoon. $S" &
img f_a4_window "Inside the dim basement, foreground: the young scientist from the reference turning startled toward a small ground-level cellar window near the ceiling. Through the window from outside: the smiling face of the salesman from the reference, holding up a hand-drawn cardboard sign next to his face reading exactly XAVE STERN. $S" --image $A/walter_young.png --image $A/xave.png &
img f_a5_backdoor "The back porch of the suburban house: the young scientist from the reference stands in the half-open backdoor in his white lab coat, arms crossed, while the salesman from the reference stands one step below on the porch stairs mid-pitch, briefcase in hand, other hand open in a persuasive gesture. Distant crowd noise implied by silhouettes around the house corner. $S" --image $A/walter_young.png --image $A/xave.png &
wait

img f_a6_lottery "On the sidewalk before the besieged house, the salesman from the reference holds up a black marker like a game-show host in front of seven science-fiction fans in costumes who hold out their open palms with large numbers written on them. Front and center: the scruffy young fan from the second reference, palm out, ecstatic. $S" --image $A/xave.png --image $A/jeremy.png &
img f_a7_jeremy "The basement lab: the scruffy young fan from the reference stands INSIDE the near glass booth, hands pressed nervously against the glass, while the young scientist stands at the wooden console, finger hovering over the blue button, and the salesman watches from the stairs with folded arms. The second identical booth visible across the room, empty. $S" --image $A/walter_young.png --image $A/xave.png --image $A/jeremy.png --image $A/booth.png &
img f_a8_mayor "The basement lab: a short round mayor in a hat and sash stands beside the salesman from the reference, staring in awe at the FAR glass booth, where a huge bodyguard in a dark suit has just materialized and wobbles, one hand on the glass, looking green. The young scientist at the console in the background. $S" --image $A/xave.png --image $A/booth.png &
img f_b1_warehouse "A vast empty warehouse hall at night, just switched-on fluorescent tubes hanging from the high ceiling, windows near the roof, moonlight outside. The young scientist from the reference stands tiny in the exact center of the empty concrete floor, arms outstretched wide, head thrown back, laughing. The salesman from the reference stands at the far door beside the light switches. $S" --image $A/walter_young.png --image $A/xave.png &
img f_b2_trailer "Night outside the warehouse: the open back of a furniture moving truck, tables and cupboards roped inside. The young woman from the reference is climbing down from the trailer, caught mid-step, while the salesman from the reference holds her arm, startled, mouth open. A police car's light in the distance. $S" --image $A/kristella.png --image $A/xave.png &
wait

img f_b3_plaza "Bright day on a white marble plaza before a Roman-style city hall with five-meter pillars. On a low stage: a single glass teleport booth like the reference machine, wrapped in black cables that run off the stage into a manhole, and a wooden lectern with a bouquet of microphones where the young woman from the reference stands in her elegant black pantsuit addressing a dense crowd of two hundred 1980s spectators. A giant projection screen beside the stage shows a live image of an identical booth in a small village square. $S" --image $A/kristella.png --image $A/booth.png &
img f_c1_temple "Interior of a teleportation station built like a white temple: mighty pillars, church-high white walls decorated with thick black cables that all converge on the ceiling, a majestic circle of a dozen glass booths like the reference machine, uniformed guards in futuristic BLUE suits, and a queue of ordinary 1980s civilians with suitcases. Above the entrance, large blue letters read exactly INSTANT. $S2" --image $A/booth.png &
img f_c2_glove "A converted hotel suite turned office: the bearded mechanic from the reference, in blue overalls and cap, holds out a work glove like an offering. The young scientist from the second reference stares down at a small dead white rat lying on the glove. Both men grave. Desk with tube monitor behind. $S" --image $A/rick.png --image $A/walter_young.png &
img f_c3_lamp "Midnight in a dark hotel suite: a single desk lamp throws a pool of light on a dissected white rat pinned open on tin foil, its organs visibly fused into one wrong glistening knot. The young scientist from the reference and the salesman from the second reference lean into the lamplight from the darkness, faces half-lit, horrified. $S" --image $A/walter_young.png --image $A/xave.png &
img f_c4_night_booth "A warm summer night on a quiet street corner: one freestanding glass teleport booth like the reference machine glowing from a blue INSTANT logo, a service phone bolted to its base. A young guard in a blue uniform stands sheepishly at the console while a giggling teenage couple is squeezed together INSIDE the single booth, flesh and palms pressed against the glass, laughing. Three more teenagers with beer bottles cheer them on. $S2" --image $A/booth.png &
wait

img f_c5_press "The entrance hall of the converted hotel headquarters: the young woman from the reference stands alone against a wall of a dozen microphones thrust at her face like hungry hydra heads, camera flashes freezing her mid-sentence, a crush of 1980s reporters. $S" --image $A/kristella.png &
img f_c6_doors "Dawn, the glass entrance doors of the hotel headquarters seen from inside: the scruffy young man from the reference has collapsed against the outside of the glass, cheek pressed to it, blood at his lips, one palm flat on the door. The young scientist from the second reference kneels on the inside, hand mirrored against the man's palm through the glass. $S" --image $A/jeremy.png --image $A/walter_young.png &
img f_d1_papers "The scientist's hotel suite drowned in crumpled paper: drifts of balled-up calculations knee-deep on the floor, equations scrawled on every surface, pencil stumps everywhere. The young scientist from the reference, wild-eyed, graphite smeared on his cheek, stands at the bulletproof window holding a pencil like a dagger, city lights beyond. $S" --image $A/walter_young.png &
img f_d2_floor5 "A dim booth-assembly floor of the hotel: ghostly rows of half-built glass booths and heaps of electronics under scattered work lamps. In the center, TWO finished booths like the reference machine wired directly together with fat cables. The salesman and the young scientist from the references carry the limp scruffy young man from the third reference toward the nearer booth. $S" --image $A/xave.png --image $A/walter_young.png --image $A/jeremy.png --image $A/booth.png &
img f_d3_couch "A hotel suite lounge: the scruffy young man from the reference sits pale on a couch wrapped in a wool blanket, holding a mug, confused. The salesman from the second reference perches on the armrest with a reassuring grin, and the young scientist from the third reference stands behind the couch, guilty. $S" --image $A/jeremy.png --image $A/xave.png --image $A/walter_young.png &
wait

img f_d4_isela "A mayoress's office at night: walls plastered with framed celebrity photos, awards and press clippings, dark brown draperies. The imperious red-haired mayoress from the reference sits behind a grand desk in a throne-like leather chair, chin on laced fingers, intrigued. The young woman from the second reference stands before the desk mid-pitch, holding a small leather bracelet. On the wall behind the mayoress, slightly apart from the awards, hangs one small framed photo of a young child. $S" --image $A/isela.png --image $A/kristella.png &
img f_e1_recluse "A once-luxurious hotel suite now filthy: stacks of yellowed newspapers, food trays, a wall of eight stacked glowing tube televisions, drawn curtains leaking one blade of daylight. The disheveled bearded recluse from the reference sits in a sunken armchair in his stained cardigan, cigarette smoke curling, while the immaculate salesman from the second reference stands in the doorway holding briefing papers, nose wrinkled. $S2" --image $A/walter_recluse.png --image $A/xave.png &
img f_e2_rescue "The same filthy hotel suite: the young woman from the reference, tears on her cheeks, fiercely hugs the shocked disheveled bearded recluse from the second reference, who stands stiff with his arms half-raised, cigarette still in one hand. Door open behind her, light spilling in. $S2" --image $A/kristella.png --image $A/walter_recluse.png &
img f_e3_station "Inside a bright INSTANT station: a small festive ceremony. The 14-year-old boy from the reference stands grinning INSIDE a glass booth like the reference machine, giving a thumbs-up through the glass. His bearded father from the second reference in overalls and cap watches proudly beside a slender brown-haired mother in a summer dress. A friendly attendant in a blue uniform stands at the console, where a small leather bracelet sits in a reader slot. Four ceiling spotlights on the booth. $S2" --image $A/bernand.png --image $A/rick.png --image $A/booth.png &
img f_e4_street "A 1990s European shopping street in the afternoon: the young woman from the reference has collapsed on the pavement on her side, one shoe off, shopping bag spilled, face gray. A group of small schoolchildren in a walking line recoils, mouths open. Passers-by turning. $S2" --image $A/kristella.png &
wait

img f_e5_control "A dark control room: a wall of eight heavy stacked CRT monitors forming one glowing map of Europe with green cable lines and blinking yellow lights, blue light washing the room. The bearded mechanic from the reference sits before it with a telephone receiver at his ear, hollow-eyed, one hand on a large key inserted into a wall socket. An open codebook on the desk. $S2" --image $A/rick.png &
img f_e6_bomb "A city street like a war zone: the glass front of a grand converted hotel has exploded outward, smoke pouring from the entrance, glass and debris across the asphalt, an overturned barricade, police lights strobing through dust, bystanders running. Dusk. $S2" &
img f_f1_roof "The flat rooftop of the headquarters at dusk, wind: a helicopter with slowing rotors behind. Two paramedics wheel a hospital gurney bearing the deathly-ill young woman from the reference - hollow cheeks, crusted lips, hair stuck to her sweat-lined face - toward a single glass booth like the reference machine. The young scientist from the second reference walks beside the gurney holding her hand, devastated. $S2" --image $A/kristella.png --image $A/walter_young.png --image $A/booth.png &
img f_f2_awake "The rooftop booth: the young woman from the reference stands in the open booth door, restored and healthy in a hospital gown, squinting in confusion at the wind, one hand on the glass. The young scientist from the second reference and the salesman from the third watch her, the scientist's eyes wet, smiling. $S2" --image $A/kristella.png --image $A/walter_young.png --image $A/xave.png --image $A/booth.png &
img f_f3_corridor "A long hotel corridor under harsh fluorescent light, night: the young scientist from the reference and the salesman from the second reference walk side by side toward camera mid-argument, the scientist staring at the floor, the salesman gesturing with an open hand. $S2" --image $A/walter_young.png --image $A/xave.png &
wait

img f_f4_green "A dim storage room: long lines of dismantled glass booths and ghostly electronics tangled in thick wires. In the center, a disfigured booth of GREEN glass connected by a single body-thick black cable to a closed dull silver metal box. The green booth's door hangs open and the bearded mechanic from the reference catches the unconscious 14-year-old boy from the second reference as he slumps out of it. Harsh single work light. $S2" --image $A/rick.png --image $A/bernand.png --image $A/booth.png &
img f_f5_room "A boy's untouched bedroom frozen in time: a street-map carpet with little toy cars, a miniature toy gas station, a box of building bricks, cartoon bedsheets. The 14-year-old boy from the reference sits unnaturally straight on the edge of the bed, hands folded neatly in his lap, pleasant blank expression, eyes empty. His bearded father from the second reference stands in the doorway, afraid of his own son. $S2" --image $A/bernand.png --image $A/rick.png &
img f_g1_interview "A top-floor interview lounge in a gleaming corporate skyscraper: floor-to-ceiling windows over a sunlit city, two designer armchairs. The dignified older scientist from the reference sits composed in a dark suit, fingers laced. Opposite him a sharp woman journalist in her 50s holds out a small dictaphone. A blue corporate logo etched subtly on the glass wall. $S2" --image $A/walter_older.png &
img f_g2_grave "An old overgrown graveyard, morning mist: the salesman from the reference, older now with gray at his temples, kneels at a moss-riddled double headstone, placing a gold pocket watch into a small hole in the earth, dried marigolds beside it. Behind him at the cemetery gate, a yellow excavator waits with its engine running, two workers leaning on it. $S2" --image $A/xave.png &
img f_g3_tent "A surreal corporate cemetery hidden under a gigantic black circus tent on a steel skeleton, night-dark inside: rows of tombstones glowing soft BLUE, each with a small digital display, manicured grass, and at the center a gothic chapel whose spire is crowned with a glowing blue corporate logo where a cross should be. The older scientist and the older salesman from the references stand tiny among the glowing graves. $S2" --image $A/walter_older.png --image $A/xave.png &
wait

# ---- Title cards ----
img t_title "Minimal film title card: elegant white serif text reading exactly WALTER'S DEAL centered on a near-black frame, behind it the faint dark silhouette of a glass teleport booth wrapped in cables, barely visible. Filmic grain." --image $A/booth.png &
img t_2years "Minimal film title card: elegant white serif text reading exactly TWO YEARS LATER centered on a pure black frame. Filmic grain, nothing else." &
img t_4years "Minimal film title card: elegant white serif text reading exactly FOUR YEARS LATER centered on a pure black frame. Filmic grain, nothing else." &
img t_6years "Minimal film title card: elegant white serif text reading exactly SIX YEARS LATER centered on a pure black frame. Filmic grain, nothing else." &
wait
echo FRAMES_DONE
