#!/bin/bash
# Walter's Deal — first pass, 480p FAST (run via walters_deal/pool_run_fast.py).
# python3 walters_deal/pool_run_fast.py walters_deal/videos_v1.sh walters_deal/outputs/video1
cd /Users/dawndrain/Code/videogen

NEG="There is no narrator and no voiceover; only characters visible on screen speak, lips moving. Photorealistic, natural human motion and facial performance, correct anatomy and proportions. No slow motion unless stated. No text, captions or subtitles appearing anywhere. Characters keep exactly the same faces, hair and clothes as in the reference images for the entire clip."
W1="Wardrobe and era lock: Walter is a lean pale man in his early 20s with short brown hair and round wire-rimmed glasses, in a white lab coat over a plaid shirt and jeans. Xave is a salesman around 45 with short black hair, sharp gray suit, red tie. Late-1980s Central Europe - absolutely no modern clothing, phones or devices."
W3="Wardrobe and era lock: Walter is the same man in his late 20s, bearded and disheveled, stained gray cardigan. Xave is a salesman around 50, short black hair, immaculate gray suit, red tie. Retro-1990s Central Europe - no modern devices."
W4="Wardrobe and era lock: Walter is the same man in his mid 30s, clean-shaven with graying temples, dark tailored suit, round glasses. Xave is around 55 with gray at his temples, immaculate charcoal suit, red tie. Retro-futurist 1990s corporate world - no modern devices."
VW="Voice lock: Walter speaks in a light, precise, slightly nasal tenor with a mild Central-European accent, hesitant and dry - the same voice in every scene, never American, never theatrical."
VX="Voice lock: Xave speaks in a smooth, confident, quick, theatrical salesman baritone - the same voice in every scene."
VK="Voice lock: Kristella speaks in a warm, wry, unhurried alto - the same voice in every scene."

gen() { :; }

# ---------- ACT I — THE DEAL ----------
gen a1_rat 10 "Cold open, midnight basement laboratory. The young scientist checks the white rat in the near glass booth, walks to the wooden console, takes a breath, and flips the round blue button. The machinery hums rising like a soprano choir, sparks crackle, the hanging lamp flickers - a blinding white flash fills the room for an instant, then silence and darkness except one lamp. The near booth is empty. He presses his hands and nose against the warm glass - then sprints across the room to the second booth, where the rat sits alive, grooming itself. Walter breaks into a huge grin. No dialogue. Locked-off static camera for the first half, then a handheld follow as he runs. ${W1} ${NEG}" --start-image $F/f_a1_basement.png --image $A/walter_young.png &

gen a2_beaming 8 "Morning kitchen. The young scientist grips the newspaper with the headline THE INVENTOR OF BEAMING, shaking it, indignant, speaking to the empty kitchen: 'Beaming. BEAMING. It has nothing to do with beaming... It is travelling.' He slaps the paper down on the table, and stares at it again in disgust. The text on the newspaper stays exactly as in the start image. ${W1} ${VW} ${NEG}" --start-image $F/f_a2_paper.png --image $A/walter_young.png &

gen a3_mob 6 "Exterior day: the small suburban house under siege - TV reporters jostling, six identical businessmen in gray suits and red ties waving contracts, costumed science-fiction fans chanting and pumping their hand-painted signs, police holding the line. General excited crowd noise, overlapping shouting, no distinct dialogue. The signs stay exactly as in the start image. ${W1} ${NEG}" --start-image $F/f_a3_mob.png &

gen a4_window 8 "Dim basement. The young scientist backs away nervously from the crowd noise above - then a sharp KNOCK-KNOCK on the small ground-level cellar window. He spins around. Outside the little window: the salesman's grinning face, and a hand-drawn cardboard sign held up beside it reading XAVE STERN. The salesman waves the sign slightly and points at it, eyebrows raised hopefully. Walter stares, baffled. The sign text stays exactly as in the start image. No dialogue. ${W1} ${NEG}" --start-image $F/f_a4_window.png --image $A/walter_young.png --image $A/xave.png &

gen a5_deal 10 "Back porch, day. The salesman on the step says smoothly: 'Let's cut the small talk. I'm here to make you a rich man.' The young scientist in the doorway, arms crossed, replies flatly: 'Me - or rather yourself?' The salesman smiles, gestures with an open hand toward the roaring crowd around the corner of the house: 'Are you sure you would trust THEM more than me?' A beat. The scientist looks at the crowd, looks back, extends his hand and says: 'Deal.' Firm handshake, the salesman's grin widens. ${W1} ${VW} ${VX} ${NEG}" --start-image $F/f_a5_backdoor.png --image $A/walter_young.png --image $A/xave.png &

gen a6_lottery 8 "Sidewalk, day. The salesman paces before seven costumed science-fiction fans like a game-show host, marker in hand: 'Ladies and gentlemen - for ONE of you, this will be the best day ever. My number is... one! Show me your hands!' Seven palms fly open with numbers scrawled on them. The scruffy young fan at the front sees his palm, leaps in the air and screams: 'YES!' The others deflate comically. ${W1} ${VX} ${NEG}" --start-image $F/f_a6_lottery.png --image $A/xave.png --image $A/jeremy.png &

gen a7_jeremy 12 "The basement lab. The scruffy young man stands inside the near glass booth, terrified and thrilled. The young scientist at the console says gravely: 'I won't let you die.' He presses the blue button. Rising choir-like hum, the floor vibrates, a blinding white flash - the near booth stands empty. Silence. Across the room the far booth now holds the young man, whole. He steps out on shaky legs. The scientist walks over and shakes his hand: 'Congratulations.' The young man smiles - then drops to his knees and vomits on the floor. The salesman, watching from the stairs, looks away with a grimace. ${W1} ${VW} ${NEG}" --start-image $F/f_a7_jeremy.png --image $A/walter_young.png --image $A/xave.png --image $A/jeremy.png &

gen a8_mayor 8 "The basement lab. The short round mayor stares at his huge bodyguard who has just materialized in the far booth and now wobbles out, hand over mouth, and vomits in the corner. The mayor claps once, overwhelmed, and stammers: 'I have to- When can we- How much do you-' and thrusts out his hand. The salesman grips it instantly with both hands, beaming. The young scientist at the console rolls his eyes slightly. ${W1} ${VX} ${NEG}" --start-image $F/f_a8_mayor.png --image $A/xave.png --image $A/walter_young.png &

# ---------- ACT II — THE DEMONSTRATION ----------
gen b1_warehouse 6 "Night. Fluorescent tubes bang on row by row over a vast empty warehouse hall. The young scientist runs to the exact center of the empty concrete floor, spreads his arms wide, turns a slow circle and shouts, voice echoing: 'This is fantastic!' The salesman leans at the far door beside the switches, satisfied. ${W1} ${VW} ${NEG}" --start-image $F/f_b1_warehouse.png --image $A/walter_young.png --image $A/xave.png &

gen b2_stowaway 8 "Night outside the warehouse. The salesman catches a young woman climbing down from the open furniture trailer and spins her around by the arm, startled. She calmly straightens her jacket and says, amused: 'Relax - I'm a fan. I come in peace.' She walks past him toward the road, then turns back with a smile: 'Kristella Attenburg. Look me up in the phone book.' He stares after her, speechless, still holding his clipboard. ${W1} ${VK} ${NEG}" --start-image $F/f_b2_trailer.png --image $A/kristella.png --image $A/xave.png &

gen b3_demo 8 "Bright day, marble plaza before the city hall, a public demonstration. The young woman at the microphone lectern proclaims proudly, savoring the moment: 'Ladies and gentlemen. We are witnessing the dawn of a new era.' Warm applause and camera flashes from the onlookers. She smiles and gestures grandly toward the glass booth beside her on the stage, presenting it. The TV camera crew pushes in closer. She rests her hand proudly on the booth's glass. ${W1} ${VK} ${NEG}" --start-image $F/f_b3_plaza2.png --image $A/kristella.png &

gen b4_sniper 6 "Same plaza, moments later, the crowd still cheering. CRACK - a distant rifle shot splits the air and the empty glass booth on stage cracks; a second CRACK and the booth shatters into a rain of glass. Screams, the crowd scatters like ants, bodyguards in dark suits pile onto the young scientist and the salesman and drag them low toward a limousine. Handheld panic camera. No dialogue, only screaming and alarms. ${W1} ${NEG}" --start-image $F/f_b3_plaza.png --image $A/walter_young.png --image $A/xave.png &

# ---------- ACT III — THE CRACKS (TWO YEARS LATER) ----------
gen c1_temple 8 "Interior of the temple-like INSTANT station, busy queue of 1980s civilians with suitcases. In one glass booth a small boy waves, a hum rises, white flash - he is gone; bystanders applaud warmly. In the neighboring booth an old man materializes, steps out carefully with his cane, looks up at the cathedral ceiling of black cables and says, trembling with wonder: 'To think that I lived long enough to experience this...' A guard in a blue uniform gently steadies him. ${NEG} Era lock: retro-futurist 1990s, temple-like white station, guards in futuristic blue uniforms, civilians in late-1980s European clothes." --start-image $F/f_c1_temple.png --image $A/booth.png &

gen c2_rat2 10 "Hotel-suite office, day. The bearded mechanic holds out the work glove. The young scientist lifts the small dead white rat from it delicately, turns it in the light, and says quietly: 'This is the first rat I ever travelled. It disappeared two years ago.' A long beat. He looks up at the mechanic: 'It hasn't decomposed.' The mechanic shifts uncomfortably, wipes his hands on his overalls. ${W1} ${VW} ${NEG} The mechanic Rick is around 40, full beard, blue overalls with suspenders, blue cap." --start-image $F/f_c2_glove.png --image $A/walter_young.png --image $A/rick.png &

gen c3_confess 10 "Midnight, one desk lamp over the dissected rat, two faces half-lit in the dark. The scientist, staring at the fused organs, says: 'You have never travelled, have you?' The salesman, quiet for once: '...Neither have you.' Silence. The scientist: 'Maybe I'm the devil.' The salesman tries a smile: 'To kill a few people?' The scientist looks up, dead calm: 'To kill everyone.' The smile dies. Locked-off static camera, no music. ${W1} ${VW} ${VX} ${NEG}" --start-image $F/f_c3_lamp.png --image $A/walter_young.png --image $A/xave.png &

gen c4_teens 8 "Night street corner, the single glowing booth. The teenage couple squeezed inside the one booth giggle, palms pressed on the glass. The young guard at the console shakes his head, smiling despite himself, and presses the button. Rising hum, white flash - the booth is empty. The teenagers outside cheer and clink beer bottles. Then the service phone bolted to the booth rings. The guard answers, and his face slowly changes to gray horror. The girl watching him stops laughing; her smile freezes. Hold on her face. No dialogue. ${NEG} Era lock: retro-1990s Europe, guard in a futuristic blue uniform, teenagers in 1990s clothes." --start-image $F/f_c4_night_booth.png &

gen c5_press 8 "Entrance hall, wall of microphones and camera flashes. The young woman, composed but pale, states: 'Our booths are designed to function with one person only.' Shouted questions overlap; one reporter's voice cuts through: 'Has Walter made a deal with the devil?' A beat. Camera flashes strobe her frozen face. She leans to the microphones and says evenly: 'No comment.' She walks out; the shouting swells. ${VK} ${NEG} Era lock: retro-1990s Europe, reporters in 1980s suits with tube-era cameras and flashbulbs." --start-image $F/f_c5_press.png --image $A/kristella.png &

gen c6_jeremy 6 "Dawn, the glass entrance doors from inside. The scruffy young man slumped against the outside of the glass, blood at his lips, breath fogging it. The scientist kneels inside, palm mirrored to his through the door, and opens it to catch him. The young man whispers: 'Is it because I was the first to travel?' The scientist, holding him: 'I'm afraid so.' ${W1} ${VW} ${NEG} Jeremy is a short scruffy man of 22, sci-fi fan t-shirt under a flannel shirt, deathly pale." --start-image $F/f_c6_doors.png --image $A/jeremy.png --image $A/walter_young.png &

# ---------- ACT IV — THE TIME MACHINE ----------
gen d1_epiphany 8 "The suite drowned in crumpled paper. The scientist, graphite on his cheek, stabs his pencil against the bulletproof window - the tip snaps and the pencil bursts; the city lights fill his glasses. He stands frozen, breathing hard. Then his eyes drop to the dead rat on the desk. Long beat. He whispers: 'Not enough time.' He snatches the rat and sprints out of frame, papers flying in his wake. ${W1} ${VW} ${NEG}" --start-image $F/f_d1_papers.png --image $A/walter_young.png &

gen d2_resurrect 12 "The dim assembly floor, two booths wired together. The salesman and the scientist fold the limp dying young man into the near booth and close the glass. The scientist types blind on the console, fingers certain, and slams a key like a conductor's downbeat. Blinding light and deafening rising noise knock the salesman back a step - at the peak the body vanishes from the near booth and reassembles in the far one. The door swings open; the young man tumbles out onto hands and knees, takes one enormous gasping breath as if tasting air for the first time, and passes out peacefully. The scientist sinks to the floor grinning with relief. No dialogue. ${W1} ${NEG}" --start-image $F/f_d2_floor5.png --image $A/walter_young.png --image $A/xave.png --image $A/jeremy.png &

gen d3_lost 8 "Hotel lounge, the young man wrapped in a blanket on the couch, mug in hand. He frowns: 'The last thing I remember is your basement. That was TWO YEARS ago?' The salesman on the armrest, breezy: 'You were famous. It was great.' The young man stares into his mug for a beat, then says flatly: 'I'm done with beaming.' The scientist behind the couch winces at the word but says nothing. ${W1} ${VX} ${NEG} Jeremy is a short scruffy man of 22 with a weak hoarse voice." --start-image $F/f_d3_couch.png --image $A/jeremy.png --image $A/xave.png --image $A/walter_young.png &

gen d4_isela 8 "The mayoress's office at night. The young woman holds up the small leather bracelet: 'Your body is saved with every trip. For a price - we restore it. Whenever you like.' The red-haired mayoress's eyes drift for one second to the small framed photo of a child on the wall, then back. She leans forward slowly, lacing her fingers: 'Which means... you can be forever young?' Beat. 'Double that.' The young woman blinks: 'Double... the price?' The mayoress smiles like a chess player. ${VK} ${NEG} Isela is an imperious mayoress of 55, red hair in a tight knot, elegant black dress, jewel necklace; she speaks in a low aristocratic purr." --start-image $F/f_d4_isela.png --image $A/isela.png --image $A/kristella.png &

# ---------- ACT V — THE FALL (FOUR YEARS LATER) ----------
gen e1_recluse 8 "The filthy suite, wall of glowing tube TVs. The bearded recluse in the armchair lights a new cigarette off the old one. The immaculate salesman at the door reads from his papers: 'Five hundred cities, my friend. We are rich beyond arithmetic.' He lowers the papers, looks at the wreck of his partner, and adds quietly: 'And between us - I don't trust an invention that scares off its own inventor. But nobody else needs to know that.' The recluse just exhales smoke at the televisions. ${W3} ${VW} ${VX} ${NEG}" --start-image $F/f_e1_recluse.png --image $A/walter_recluse.png --image $A/xave.png &

gen e2_rescue 8 "The filthy suite. The young woman, tears on her cheeks, squeezes the stunned bearded recluse in a fierce hug; his arms hang, cigarette dangling. She pulls back, holds his face, looks him over and declares through the tears: 'You look like crap. Your room looks like crap.' She spins him by the shoulders and marches him toward the bathroom: 'You're not coming out of there before you smell like roses.' He stumbles along, protesting wordlessly. ${W3} ${VK} ${NEG}" --start-image $F/f_e2_rescue.png --image $A/kristella.png --image $A/walter_recluse.png &

gen e3_bernand 10 "Bright station, the little ceremony. The father in overalls grins at his son in the booth: 'It's like saving a game on your Nintendo.' The boy rolls his eyes through the glass: 'It's called PlayStation.' The attendant presses the console; three warm chimes sound; the boy gives a thumbs-up - then the floor ring flips to white, turbines ROAR, a hard flash - and the booth is empty. The small leather bracelet clatters into the console tray. Bystanders applaud, someone whistles, not understanding. The father and mother stand frozen, faces draining. Hold. ${VW} ${NEG} Era lock: retro-1990s station, attendant in blue uniform; Rick is a bearded mechanic of 45 in overalls and cap; Bernand is a 14-year-old boy in a striped t-shirt; Rick speaks in a warm gravelly baritone, the boy in a bored teenage voice." --start-image $F/f_e3_station.png --image $A/rick.png --image $A/bernand.png &

gen e4_collapse 6 "European shopping street, afternoon. The young woman walks unsteadily, stops, puts a hand on a lamppost, doubles over and vomits into the gutter - then her knees fold and she hits the pavement on her side. A line of small schoolchildren recoils screaming; a shopkeeper runs out. Handheld. No dialogue. ${NEG} Kristella wears an elegant 1990s skirt suit; retro-1990s European street, no modern cars." --start-image $F/f_e4_street.png --image $A/kristella.png &

gen e5_shutdown 8 "The dark control room, the CRT wall-map of Europe glowing green. The bearded mechanic listens at the telephone receiver, ashen, and repeats for the room: 'Walter says shut it all down. ...No more blood on our hands.' A beat - his own son's photo is taped to the console edge. He turns the big key in the wall socket. On the map, the green lines blink out one by one until the whole continent goes dark. He lets the codebook slide from his hand to the floor and sinks back in the chair. ${NEG} Rick is a bearded mechanic of 45 in blue overalls and cap, hollow-eyed, and speaks in a cracked gravelly baritone." --start-image $F/f_e5_control.png --image $A/rick.png &

gen e6_bomb 6 "City street at dusk. A muffled boom - the glass front of the grand hotel headquarters erupts outward in a slow bloom of glass and smoke; alarms wail, papers rain, police lights strobe through the dust, silhouettes run. The camera holds locked-off across the street, unflinching. No dialogue. ${NEG}" --start-image $F/f_e6_bomb.png &

# ---------- ACT VI — RESURRECTIONS ----------
gen f1_sorry 10 "Rooftop at dusk, helicopter wind whipping coats. Paramedics wheel the dying woman's gurney to the booth; the scientist walks alongside holding her limp hand. They lift her in; the glass closes on her hollow face. The scientist rests his hand on the console key, closes his eyes, and whispers, barely audible under the wind: 'Kristella. I'm sorry.' He presses the key like a man signing a confession. Rising hum, the frame floods with white light. ${VW} ${NEG} Era lock: retro-1990s; Walter is in his late 20s, clean-shaven again, dark shirt; Kristella is deathly ill, crusted lips, gray skin, hospital blanket." --start-image $F/f_f1_roof.png --image $A/walter_young.png --image $A/kristella.png &

gen f2_awake 8 "The light dies. The booth door swings open and the young woman steps out healthy, color in her cheeks, squinting against the rooftop wind in her hospital gown. She looks at the stunned men and demands, groggy and annoyed: 'What the fuck, guys. What time is it?' Beat. 'And where did the coffee machine go?' The scientist laughs once - wet eyes, a broken smile - turns, and walks away across the roof while the salesman moves in to steady her. ${VK} ${NEG} Era lock: retro-1990s rooftop; Walter late 20s clean-shaven, dark shirt; Xave in his gray suit." --start-image $F/f_f2_awake.png --image $A/kristella.png --image $A/walter_young.png --image $A/xave.png &

gen f3_price 6 "Hotel corridor, night, harsh fluorescents. Walking side by side. The salesman, matter-of-fact: 'The save was four years old.' The scientist stops. Stares at the floor: 'Four years. Everything we were - she doesn't remember any of it.' The salesman puts a hand on his shoulder in passing and keeps walking: 'She's alive. You're welcome.' The scientist stands alone under the buzzing light. ${W3} ${VW} ${VX} ${NEG} Walter is clean-shaven here, dark shirt." --start-image $F/f_f3_corridor.png --image $A/walter_young.png --image $A/xave.png &

gen f4_catch 6 "The dim storage room, the disfigured green glass booth. Machine rhythm builds, an unbearable rising whine, blinding light from the green glass - then silence. The door swings open and the unconscious boy slumps out into his father's arms; the father folds to his knees holding him, rocking, weeping with relief. The silver box in the corner hums. No dialogue. Locked-off static camera. ${NEG} Rick is a bearded mechanic of 45 in overalls; Bernand is a 14-year-old boy in a striped t-shirt." --start-image $F/f_f4_green.png --image $A/rick.png --image $A/bernand.png &

gen f5_inside 8 "The boy's untouched bedroom. The boy sits unnaturally straight on the bed's edge, hands folded, pleasant and empty. His father watches from the doorway. The boy says, flat and polite: 'It's no big deal, father.' A beat. He turns his head a little too smoothly toward the door: 'Let's go back together.' Another beat. 'Back inside.' He smiles - a smile that does not reach his eyes. Hold on the father's face going cold. ${NEG} Rick is a bearded mechanic of 45; Bernand is a 14-year-old boy in a striped t-shirt who speaks in a flat, courteous, uninflected child's voice." --start-image $F/f_f5_room.png --image $A/bernand.png --image $A/rick.png &

# ---------- ACT VII — THE CEMETERY (SIX YEARS LATER) ----------
gen g1_interview 8 "Top-floor interview lounge, sun over the city. The journalist holds out her dictaphone: 'They say you and Mr. Stern never use INSTANT yourselves.' Silence. The older scientist holds her gaze, the city humming far below. Five full seconds. Then, perfectly composed: '...Next question.' She smiles like she got her answer. ${W4} ${VW} ${NEG} The journalist is a sharp woman in her 50s in a 1990s skirt suit with a clear professional voice." --start-image $F/f_g1_interview.png --image $A/walter_older.png &

gen g2_grave 8 "The overgrown graveyard, morning mist. The older salesman pats the earth flat over the small hole at the mossy double headstone, stands, brushes his knees, and looks at the grave a long moment. Then he turns, raises one arm to the excavator idling at the gate, and calls out, businesslike: 'And that's graveyard number ten.' He walks away; the excavator lurches forward past him into the cemetery. ${W4} ${VX} ${NEG}" --start-image $F/f_g2_grave.png --image $A/xave.png &

gen g3_funeral 10 "Under the giant black tent: rows of tombstones glowing soft blue, the gothic chapel with the glowing corporate logo where a cross should be. The two older men walk slowly between the graves. The scientist, deadpan: 'What if I was the first to use our own INSTANT funeral service?' The salesman doesn't miss a beat: 'We both know that would be the first time you'd use INSTANT...' - he lets it hang - 'anything.' The scientist actually laughs, once, and it echoes wrong under the tent. ${W4} ${VW} ${VX} ${NEG}" --start-image $F/f_g3_tent.png --image $A/walter_older.png --image $A/xave.png &

gen g4_end 10 "The same blue-glowing cemetery, wider: two small men among the graves. The scientist looks up at the black tent ceiling where a sky should be: 'Sometimes I stop and wonder where this is all going to end.' He turns to his partner: 'Don't you ever ask yourself that question?' The salesman opens his mouth for a comeback - and nothing comes. His mood tilts. He drifts off and stares down at the grass at his feet. The scientist watches him. Hold the silence for the last three seconds, only the hum of the tombstones. ${W4} ${VW} ${NEG}" --start-image $F/f_g3_tent.png --image $A/walter_older.png --image $A/xave.png &

echo BATCH_DEFINED
