#!/bin/bash
# The Hork-Bajir Chronicles — first full pass (42 shots).
# Run: python3 pool_run.py animorphs/videos_hb1.sh animorphs/outputs/hb1
# All paths relative to repo root (pool_run runs gen.py with cwd=ROOT).

HB="Species lock: Hork-Bajir are seven-foot bipedal aliens with leathery green-brown skin, a crest of bone blades raked back from the skull, large curved blades on forearms, elbows and knees, a spiked tail, tyrannosaur legs, a hawk-beaked gentle face with large green eyes, wearing only a woven bark loincloth. They match the reference images exactly."
AND="Species lock: Andalites are graceful alien centaurs with blue-and-tan fur, four legs, two slender arms, two extra eyes on stalks atop the head, a long tail with a scythe blade, and NO mouth. Andalite speech is telepathic: their calm voice is heard while the face stays completely still - no mouth, no lip movement, ever."
DAKV="Voice lock: Dak Hamee speaks aloud in the same deep, warm, gravelly, unhurried voice as the rest of the film, simple careful diction, beak moving naturally."
ALDV="Voice lock: Aldrea's telepathic voice is the same clear, young, slightly formal female voice as the rest of the film - never American-casual, never childish."
ESPV="Voice lock: Esplin 9466 speaks through his host's mouth in the same cold, precise, silky, unhurried male voice as the rest of the film."
NEG="Photorealistic epic sci-fi film, natural creature motion, correct anatomy. No random camera zooms or drift; camera only as stated. No slow motion unless stated. No text, captions or subtitles anywhere. There is no narrator and no voiceover; only characters visible on screen speak. Characters keep exactly the same bodies, faces, blades, fur and colors as in the reference images for the entire clip."

# ---- Act 0: frame story ----
gen f1 6 "Aerial wildlife shot: a red-tailed hawk rides a thermal over a hidden Sierra Nevada valley at golden hour, wings barely moving, drifting in a slow circle over pines and a creek. Wind and distant birdsong. No dialogue. ${NEG}" --start-image animorphs/frames/f1.png --image animorphs/anchors/tobias.png
gen f2 10 "The red-tailed hawk perches still on a low branch, head cocked, firelight flickering. The old scarred Hork-Bajir sitting on the log leans forward and speaks slowly, warmly, in a deep old gravelly voice: 'Come, Tobias. Sit. I tell you story. Story of before. Story of Dak Hamee... and Aldrea.' Fire crackle, evening crickets. ${HB} ${NEG}" --start-image animorphs/frames/f2.png --image animorphs/anchors/jara.png --image animorphs/anchors/tobias.png
gen f3 5 "Title card: the enormous carved bone-white letters reading 'THE HORK-BAJIR CHRONICLES' hang over the vast alien tree valley; mist drifts slowly between the colossal trunks, pollen sparkles, a low orchestral swell. The letters stay EXACTLY as in the start image, unchanged. No dialogue. ${NEG}" --start-image animorphs/frames/f3.png

# ---- Act 1: exile ----
gen a1 8 "The vast ivory Andalite dome ship descends slowly and silently through pale sky toward the canopy of trees two kilometers tall, dwarfed by them. Drifting pollen, deep engine hum, alien birdcalls. Locked-off wide camera. No dialogue. ${NEG}" --start-image animorphs/frames/a1.png
gen a2 12 "Inside the dome at dusk. The young Andalite female paces angrily behind her father, her telepathic voice sharp: 'You were a prince, father. Now they send you to watch trees grow at the edge of nowhere.' The old Andalite keeps gazing at the valley, and answers slowly, heavy with regret: 'I gave the Yeerks the stars, Aldrea. Kindness was my crime. We will not speak of it again.' Neither face moves - Andalites have no mouths. ${AND} ${ALDV} Seerow's telepathic voice is old, gentle and tired. ${NEG}" --start-image animorphs/frames/a2.png --image animorphs/anchors/seerow.png --image animorphs/anchors/aldrea.png
gen a3 6 "The young Andalite female gallops joyously at full stride along the grassy ridge above the colossal-tree valley, tail streaming, stalk eyes swiveling to drink in the view, golden light flaring. Hooves drumming, wind. No dialogue. ${AND} ${NEG}" --start-image animorphs/frames/a3.png --image animorphs/anchors/aldrea.png

# ---- Act 2: Dak ----
gen b1 8 "Pastoral alien life: on a branch wide as a road, several Hork-Bajir of different sizes calmly strip bark with their wrist blades and eat it; a small child chases drifting pollen; mist rolls far below. Gentle creaks, birdsong, contented low grunts. Slow locked-off wide shot. No dialogue. ${HB} ${NEG}" --start-image animorphs/frames/b1.png --image animorphs/anchors/dak.png --image animorphs/anchors/jagil.png
gen b2 10 "Close on the young Hork-Bajir drawing careful circles in pale bark-dust with one claw. The stockier bark-brown one peers over his shoulder and asks, puzzled, in a slow gravelly voice: 'Dak Hamee make shapes. Why make shapes?' Dak looks up at the sky through the canopy and answers with quiet wonder: 'It is the sky, Jagil. The lights move. I watched. They move in circles.' ${HB} ${DAKV} Jagil's voice is slower and simpler than Dak's. ${NEG}" --start-image animorphs/frames/b2.png --image animorphs/anchors/dak.png --image animorphs/anchors/jagil.png
gen b3 8 "The ancient grey Hork-Bajir elder raises both bladed arms over the kneeling young seer and pronounces solemnly, voice cracked with age: 'Dak Hamee is seer. Born one time in all times. Seer come when change come.' The watching circle of Hork-Bajir murmurs. Dusk light, valley mist. ${HB} ${NEG}" --start-image animorphs/frames/b3.png --image animorphs/anchors/dak.png
gen b4 10 "First meeting, wary and slow: the young Hork-Bajir freezes mid-step and stares. He speaks first, halting: 'You are not of the trees. Not of the valley.' The Andalite holds very still, tail blade lowered, and her clear telepathic voice answers: 'No. I am Aldrea. I come from the sky you watch.' Her face never moves - no mouth. ${HB} ${AND} ${DAKV} ${ALDV} ${NEG}" --start-image animorphs/frames/b4.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen b5 12 "Night. A blue holographic star map spins slowly between them, painting both faces with light. Aldrea's telepathic voice, gentle, teaching: 'That light is not a hole in the sky, Dak. It is a sun. Like yours. And around it - worlds.' Dak reaches one careful claw toward a tiny projected world, and breathes: 'Worlds. Dak wants to see.' The hologram stars drift. ${HB} ${AND} ${DAKV} ${ALDV} ${NEG}" --start-image animorphs/frames/b5.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen b6 8 "Comedy beat: the Andalite leaps from one branch toward another, lands badly, all four legs splaying, skids to a graceless stop in a puff of moss. The young Hork-Bajir throws his head back and laughs - a big honking joyful laugh - and points at her: 'Andalite falls like stone!' Her stalk eyes glare at him with wounded dignity. ${HB} ${AND} ${DAKV} ${NEG}" --start-image animorphs/frames/b6.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png

# ---- Act 3: the Deep / the Arn ----
gen c1 8 "They climb down a root the size of a cathedral wall into blue bioluminescent darkness, the Hork-Bajir moving easily, the Andalite picking her way. Her telepathic voice echoes softly: 'My father's instruments found something below the Deep, Dak. Something old. Something alive.' Dripping water, deep sub-bass rumble. ${HB} ${AND} ${ALDV} ${NEG}" --start-image animorphs/frames/c1.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen c2 8 "Horror beat: out of the black mist a whale-sized armored monster with too many jaws lunges roaring; the two small figures scramble up the root barely ahead of snapping teeth; bioluminescent fungus scatters glowing spores; the monster crashes back into the dark. Screeching roar, cracking wood. No dialogue. ${HB} ${AND} ${NEG}" --start-image animorphs/frames/c2.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen c3 8 "Reveal: the two tiny silhouettes stand on a ledge as the hidden cavern city of amber and jade towers glows below them, terraced gardens shimmering. Slow awed push-in past their shoulders. Dak whispers: 'What... is this place?' Choral hum, distant chimes. ${HB} ${DAKV} ${NEG}" --start-image animorphs/frames/c3.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen c4 8 "The small iridescent Arn stalks toward the two intruders on the amber terrace, crest flaring crimson, one thin arm pointing at the Hork-Bajir, and speaks in a reedy, haughty, aristocratic voice: 'Hork-Bajir. On MY doorstep. You were not made to ask questions.' ${HB} ${AND} The Arn's small mouth moves precisely as it speaks. ${NEG}" --start-image animorphs/frames/c4.png --image animorphs/anchors/arn.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen c5 12 "The Arn sweeps a thin arm along the wall of turquoise gene-tanks with embryonic Hork-Bajir shapes floating inside, and declaims, proud and pitiless, in its reedy aristocratic voice: 'Long ago the sky burned. We made the trees to heal the air. And we made YOU - to tend the trees. Gardeners. Tools. Nothing more.' The young Hork-Bajir stares at his own reflection in the tank glass over a floating embryo, frozen. ${HB} ${NEG}" --start-image animorphs/frames/c5.png --image animorphs/anchors/arn.png --image animorphs/anchors/dak.png
gen c6 12 "Quiet devastation in blue fungal light. Dak sits slumped on the great root, staring at his own open claws, and says slowly, hollowed out: 'I am not a people. I am a tool that learned to dream.' Aldrea steps close, lays her slim hand on his shoulder, and her telepathic voice answers, fierce and gentle: 'A tool cannot choose, Dak. You choose. That makes you a people.' ${HB} ${AND} ${DAKV} ${ALDV} ${NEG}" --start-image animorphs/frames/c6.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png

# ---- Act 4: the Yeerks arrive ----
gen d1 6 "Dread: a formation of cockroach-like gunmetal bug fighters with twin forward spear-points slides down silently through the pale sky between the colossal trees, engine glow reflecting off teal canopy. Low menacing hum builds. Locked-off wide. No dialogue. ${NEG}" --start-image animorphs/frames/d1.png
gen d2 10 "On the dark pool ship bridge, the harnessed Hork-Bajir-Controller studies a rotating tactical hologram of the tree world and speaks in a cold, precise, silky voice, savoring it: 'Scans show no weapons. No metal. No fire. Only bodies. Billions of strong... bladed... bodies.' Orange light plays over his cruel eyes. ${HB} ${ESPV} ${NEG}" --start-image animorphs/frames/d2.png --image animorphs/anchors/esplin.png
gen d3 8 "Night horror, discreet: at the freshly dug earthen pool under harsh portable lights, armed Hork-Bajir guards steer a line of unarmed Hork-Bajir forward; at the water's edge one is pressed slowly to kneel, head bowed toward the steaming grey liquid; steam drifts across and the shot holds on the watching line. Muffled whimpers, industrial hum. No dialogue, no gore. ${HB} ${NEG}" --start-image animorphs/frames/d3.png --image animorphs/anchors/dak.png
gen d4 12 "Dusk. Dak searches his friend's face, worried, speaking carefully: 'Jagil. You did not eat. You do not laugh. Where does Jagil go at night?' The stocky bark-brown Hork-Bajir stands too still, and answers in a flat, dead, wrong voice: 'Jagil is here. Jagil is... better now.' A beat of silence; Dak's eyes narrow with fear. ${HB} ${DAKV} ${NEG}" --start-image animorphs/frames/d4.png --image animorphs/anchors/dak.png --image animorphs/anchors/jagil.png
gen d5 8 "Night attack: crimson energy beams rake the geodesic dome, panels bursting into fire; the old Andalite wheels toward his daughter, main eyes wide, and his telepathic voice cracks like thunder: 'Aldrea - RUN!' She gallops from the blast light as a beam strikes behind her. Explosions, shattering panels. ${AND} Seerow's telepathic voice is old and desperate. ${NEG}" --start-image animorphs/frames/d5.png --image animorphs/anchors/seerow.png --image animorphs/anchors/aldrea.png
gen d6 10 "Grey dawn. The young Andalite walks slowly through the smoking skeleton of the dome, ash drifting like snow. Her telepathic voice is flat, numb, barely holding: 'Father. Mother. Barafin. All of them. They are all of them dead.' Only wind and settling embers. Her face never moves. ${AND} ${ALDV} ${NEG}" --start-image animorphs/frames/d6.png --image animorphs/anchors/aldrea.png

# ---- Act 5: resistance ----
gen e1 12 "Storm-grey morning argument. Aldrea leans toward Dak, telepathic voice urgent: 'The Yeerks take bodies, Dak. They will take every Hork-Bajir in the world unless we fight.' Dak turns half away, gripping the bark: 'Hork-Bajir do not fight. Hork-Bajir do not even have a word for war.' Aldrea steps closer, quiet and hard: 'Then we will teach them one.' ${HB} ${AND} ${DAKV} ${ALDV} ${NEG}" --start-image animorphs/frames/e1.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen e2 8 "Strange quiet moment: Aldrea presses her slim many-fingered hand flat on Dak's chest. His eyes drift calm and unfocused, trance-like; a faint shimmer passes between them. Dak murmurs, dreamy: 'What do you do?' Aldrea, softly: 'Borrowing. Watch.' ${HB} ${AND} ${DAKV} ${ALDV} ${NEG}" --start-image animorphs/frames/e2.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen e3 8 "Signature VFX shot, sunrise backlight: the Andalite's morph flows - blue fur receding into leathery green-brown skin, the four legs fusing into two powerful ones, stalk eyes sinking away, bone blades erupting from skull and forearms - until a female Hork-Bajir with a blue-grey sheen stands where the Andalite was, flexing new claws. Organic shifting sounds, awe not horror. No dialogue. ${NEG}" --start-image animorphs/frames/e3.png --image animorphs/anchors/aldrea.png --image animorphs/anchors/aldrea_hb.png
gen e4 8 "Training: Dak demonstrates a slow blade-block stance before a ragged line of free Hork-Bajir who copy him clumsily; the blue-sheened female corrects one recruit's arm. Dak calls out steadily: 'Blades were for bark. Now blades must be for blades.' Rain begins. ${HB} ${DAKV} ${NEG}" --start-image animorphs/frames/e4.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea_hb.png
gen e5 12 "After the ambush, rain: Dak stands over the fallen enemy Hork-Bajir in its black-and-crimson harness, his blades lowered, chest heaving, and speaks with grief, almost to himself: 'He was Hork-Bajir too. The Yeerk was in his head - but the blood is Hork-Bajir blood. What are we becoming?' The free Hork-Bajir behind him look away. Rain hiss. No gore. ${HB} ${DAKV} ${NEG}" --start-image animorphs/frames/e5.png --image animorphs/anchors/dak.png
gen e6 12 "Pool ship bridge. The Controller commander turns slowly from the flickering battle-report hologram, head tilting with predatory delight, and purrs in his cold silky voice: 'A resistance. Led by an Andalite. Interesting.' He steps toward the viewport, hands clasping behind his back: 'Tell the Sub-Visser I want that blue body taken alive. Someday... it will be mine.' ${HB} ${ESPV} ${NEG}" --start-image animorphs/frames/e6.png --image animorphs/anchors/esplin.png

# ---- Act 6: Alloran and the virus ----
gen g1 8 "Dawn on the scorched ridge: eight sleek ivory Andalite fighters stand in a row; the scarred war-prince surveys the smoke rising from the valley and his clipped, cold telepathic voice states flatly: 'Eight warriors. That is what the council sends. Eight - for a world already lost.' His tail blade flicks. ${AND} Alloran's telepathic voice is clipped, commanding, contemptuous. ${NEG}" --start-image animorphs/frames/g1.png --image animorphs/anchors/alloran.png
gen g2 12 "Face-off in the dome wreckage, circling slowly, tails half-raised. Alloran, cold: 'Your father's kindness armed the enemy, child. Sentiment is how wars are lost.' Aldrea, blazing: 'And what do you call eight million Hork-Bajir, War-Prince? Acceptable losses?' Their tail blades hover a hand apart. Neither face moves. ${AND} ${ALDV} Alloran's telepathic voice is clipped and commanding. ${NEG}" --start-image animorphs/frames/g2.png --image animorphs/anchors/alloran.png --image animorphs/anchors/aldrea.png
gen g3 8 "Close-up: the war-prince's many-fingered hand raises the small crystalline vial; sickly blue-white light swirls inside like trapped smoke, reflecting in his cold main eyes. His telepathic voice, quiet and final: 'If the Yeerks want Hork-Bajir bodies... we deny them the bodies.' ${AND} Alloran's telepathic voice is clipped and cold. ${NEG}" --start-image animorphs/frames/g3.png --image animorphs/anchors/alloran.png
gen g4 8 "Night heist, tense and silent: Dak and Aldrea slip between the sleeping ivory fighter craft, moving low through moonlight and long shadows; Dak cradles the glowing vial against his chest; a sentry's stalk eyes turn and they freeze against a hull until it looks away. Crickets, held breath. No dialogue. ${HB} ${AND} ${NEG}" --start-image animorphs/frames/g4.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen g5 8 "Ambush chaos at night: crimson dracon beams streak the dark, bark exploding; Dak is thrown backward clutching his side; the glowing vial spins from his open claw, falls away into the black abyss between branches and bursts into a spreading blue-white mist far below. Aldrea screams his name telepathically: 'DAK!' ${HB} ${AND} ${ALDV} ${NEG}" --start-image animorphs/frames/g5.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea.png
gen g6 8 "Devastation, dead silence: slow drift across the valley - grey peeling bark, empty branches, no movement anywhere, pale spores sifting down like ash through cold shafts of light. Only faint wind. No dialogue, no characters. ${NEG}" --start-image animorphs/frames/g6.png

# ---- Act 7: nothlit / last stand ----
gen h1 12 "Sunrise between them. Dak, wounded side bound with woven bark, looks at the blue-sheened female Hork-Bajir and says softly, dreading the answer: 'Aldrea. The sun rises. Your two hours...' She steps closer, calm, resolved, and answers in Aldrea's clear voice - now spoken aloud through a Hork-Bajir mouth, gentle and sure: 'Passed long ago, Dak Hamee. I am Hork-Bajir now. Your people are my people. Your fight is my fight.' Their foreheads touch, blades carefully apart. ${HB} ${DAKV} Aldrea now speaks aloud in the same clear formal young female voice as her telepathic voice. ${NEG}" --start-image animorphs/frames/h1.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea_hb.png
gen h2 10 "The highest thin branches above the clouds, dawn: the small ragged band of free Hork-Bajir in the woven hide - males, females, two children. Dak stands watch at the edge and speaks quietly, steady as stone: 'The Yeerks take the world. They do not take all. While one Hork-Bajir is free - Hork-Bajir are free.' Wind, creaking branches. ${HB} ${DAKV} ${NEG}" --start-image animorphs/frames/h2.png --image animorphs/anchors/dak.png --image animorphs/anchors/aldrea_hb.png
gen h3 12 "Epilogue: alone at the tall viewport, the conquered green world turning below, the Controller commander watches the stars, hands behind his back, and says quietly to no one, in his cold silky voice: 'Sub-Visser Esplin. Nine-four-double-six.' A slow breath, savoring. 'Next - the Andalite home world. Next... everything.' ${HB} ${ESPV} ${NEG}" --start-image animorphs/frames/h3.png --image animorphs/anchors/esplin.png

# ---- Act 8: frame close ----
gen i1 10 "Dusk on Earth, embers rising. The old scarred Hork-Bajir spreads both bladed arms wide, finishing the tale in his deep old gravelly voice: 'Dak and Aldrea fight long. Fight until end. Their kawatnoj - their children's children - still free.' The hawk on the branch shifts its wings. ${HB} ${NEG}" --start-image animorphs/frames/i1.png --image animorphs/anchors/jara.png --image animorphs/anchors/tobias.png
gen i2 12 "The slender adolescent female Hork-Bajir steps into the firelight and stands straight. The old one says with quiet pride: 'This is Toby. Toby Hamee. Named for you, Tobias.' The young one looks directly at the hawk and speaks clearly, in a young bright voice with gravel underneath: 'I am a seer, like Dak. I see what others do not see. I see us free.' ${HB} ${NEG}" --start-image animorphs/frames/i2.png --image animorphs/anchors/toby.png --image animorphs/anchors/jara.png --image animorphs/anchors/tobias.png
gen i3 8 "Final shot: the red-tailed hawk lifts from the pine branch and flies out over the darkening valley into the deep orange sunset, wings wide, one bright star above; the camera holds as it shrinks to a speck. Wind, one distant hawk cry. Slow fade to black at the very end. No dialogue. ${NEG}" --start-image animorphs/frames/i3.png --image animorphs/anchors/tobias.png
